[package]
name = "frostclip"
version = "0.0.1"
edition = "2024"

[dependencies]
ffmpeg-sys-next = "8.1"
ffmpeg-next = "8.1"
tracing = "0.1.44"

pipewire = "0.10"
libspa = "0.10"

[dependencies.logging_subscriber]
git = "https://gitlab.com/invra/logging_subscriber"

[dependencies.chrono]
version = "0.4.45"
default-features = false
features = [
  "std",
  "clock",
]
