name: Dev Build

on:
  push:
  pull_request:

jobs:
  dev:
    strategy:
      matrix:
        include:
          - os: windows-latest
            just-target: windows-dev
            artifact: build/frostclip-windows-dev.exe
            name: frostclip-dev-windows

          - os: ubuntu-latest
            just-target: linux-dev
            artifact: build/frostclip-linux-dev
            name: frostclip-dev-linux

          - os: macos-latest
            just-target: mac-dev
            artifact: build/frostclip-mac-dev
            name: frostclip-dev-mac

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install Just
        uses: extractions/setup-just@v4

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y \
            pkg-config \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libavfilter-dev \
            libswscale-dev \
            libva-dev \
            libva-drm2

      - name: Format check
        run: cargo fmt --check

      - name: Build
        run: just ${{ matrix.just-target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.artifact }}
          retention-days: 7
