name: Dev Build

on:
  push:
  pull_request:

jobs:
  dev:
    strategy:
      matrix:
        include:
          - os: windows-latest
            just-target: windows-dev
            artifacts: frostclip.exe
            name: frostclip-dev-windows
          - os: ubuntu-latest
            just-target: linux-dev
            artifacts: frostclip-linux
            name: frostclip-dev-linux
          - os: macos-latest
            just-target: mac-dev
            artifacts: frostclip-macos
            name: frostclip-dev-macos

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Build
        run: just ${{ matrix.just-target }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.artifacts }}
          retention-days: 7
